// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPqO5j0mjYb5ktoG26AxQdjoiotqpJbLw',
    appId: '1:979647511982:android:7c11b13449079a1c09dc3f',
    messagingSenderId: '979647511982',
    projectId: 'drbalcony-24e1d',
    storageBucket: 'drbalcony-24e1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUtEYS3SRmvVCzhk_x3lzMgfkJhdScDBA',
    appId: '1:979647511982:ios:20f45286ba683ea609dc3f',
    messagingSenderId: '979647511982',
    projectId: 'drbalcony-24e1d',
    storageBucket: 'drbalcony-24e1d.appspot.com',
    androidClientId: '979647511982-8lqmhatuvtg8ug3s6omvb801m8o5fgsu.apps.googleusercontent.com',
    iosClientId: '979647511982-7e86hqg93hsap7fgg22nb1dgki0tupn1.apps.googleusercontent.com',
    iosBundleId: 'com.drbalcony.drbalcony',
  );
}
